name: Velog Backup

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # 매일 오전 9시 (KST)
  workflow_dispatch: # 수동 실행 버튼 활성화

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Velog Backup Action
        uses: gaemi/velog-backup@v0.2.0
        with:
          # 본인의 벨로그 아이디를 입력하세요
          user_id: '본인의_벨로그_아이디'
          # 폴더 이름을 지정할 수 있습니다 (기본값은 posts)
          folder: 'TIL'
